// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.2
// source: api/imgcropper/service/imgcroper.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImgcroperClient is the client API for Imgcroper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImgcroperClient interface {
	CropImg(ctx context.Context, in *CropImgRequest, opts ...grpc.CallOption) (*CropImgReply, error)
}

type imgcroperClient struct {
	cc grpc.ClientConnInterface
}

func NewImgcroperClient(cc grpc.ClientConnInterface) ImgcroperClient {
	return &imgcroperClient{cc}
}

func (c *imgcroperClient) CropImg(ctx context.Context, in *CropImgRequest, opts ...grpc.CallOption) (*CropImgReply, error) {
	out := new(CropImgReply)
	err := c.cc.Invoke(ctx, "/api.imgcropper.service.Imgcroper/CropImg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImgcroperServer is the server API for Imgcroper service.
// All implementations must embed UnimplementedImgcroperServer
// for forward compatibility
type ImgcroperServer interface {
	CropImg(context.Context, *CropImgRequest) (*CropImgReply, error)
	mustEmbedUnimplementedImgcroperServer()
}

// UnimplementedImgcroperServer must be embedded to have forward compatible implementations.
type UnimplementedImgcroperServer struct {
}

func (UnimplementedImgcroperServer) CropImg(context.Context, *CropImgRequest) (*CropImgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CropImg not implemented")
}
func (UnimplementedImgcroperServer) mustEmbedUnimplementedImgcroperServer() {}

// UnsafeImgcroperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImgcroperServer will
// result in compilation errors.
type UnsafeImgcroperServer interface {
	mustEmbedUnimplementedImgcroperServer()
}

func RegisterImgcroperServer(s grpc.ServiceRegistrar, srv ImgcroperServer) {
	s.RegisterService(&Imgcroper_ServiceDesc, srv)
}

func _Imgcroper_CropImg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CropImgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgcroperServer).CropImg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.imgcropper.service.Imgcroper/CropImg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgcroperServer).CropImg(ctx, req.(*CropImgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Imgcroper_ServiceDesc is the grpc.ServiceDesc for Imgcroper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Imgcroper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.imgcropper.service.Imgcroper",
	HandlerType: (*ImgcroperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CropImg",
			Handler:    _Imgcroper_CropImg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/imgcropper/service/imgcroper.proto",
}
