// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.2
// source: imgcropper.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImgcropperClient is the client API for Imgcropper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImgcropperClient interface {
	CropImg(ctx context.Context, in *CropImgRequest, opts ...grpc.CallOption) (*CropImgReply, error)
}

type imgcropperClient struct {
	cc grpc.ClientConnInterface
}

func NewImgcropperClient(cc grpc.ClientConnInterface) ImgcropperClient {
	return &imgcropperClient{cc}
}

func (c *imgcropperClient) CropImg(ctx context.Context, in *CropImgRequest, opts ...grpc.CallOption) (*CropImgReply, error) {
	out := new(CropImgReply)
	err := c.cc.Invoke(ctx, "/api.imgcropper.service.Imgcropper/CropImg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImgcropperServer is the server API for Imgcropper service.
// All implementations must embed UnimplementedImgcropperServer
// for forward compatibility
type ImgcropperServer interface {
	CropImg(context.Context, *CropImgRequest) (*CropImgReply, error)
	mustEmbedUnimplementedImgcropperServer()
}

// UnimplementedImgcropperServer must be embedded to have forward compatible implementations.
type UnimplementedImgcropperServer struct {
}

func (UnimplementedImgcropperServer) CropImg(context.Context, *CropImgRequest) (*CropImgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CropImg not implemented")
}
func (UnimplementedImgcropperServer) mustEmbedUnimplementedImgcropperServer() {}

// UnsafeImgcropperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImgcropperServer will
// result in compilation errors.
type UnsafeImgcropperServer interface {
	mustEmbedUnimplementedImgcropperServer()
}

func RegisterImgcropperServer(s grpc.ServiceRegistrar, srv ImgcropperServer) {
	s.RegisterService(&Imgcropper_ServiceDesc, srv)
}

func _Imgcropper_CropImg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CropImgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImgcropperServer).CropImg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.imgcropper.service.Imgcropper/CropImg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImgcropperServer).CropImg(ctx, req.(*CropImgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Imgcropper_ServiceDesc is the grpc.ServiceDesc for Imgcropper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Imgcropper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.imgcropper.service.Imgcropper",
	HandlerType: (*ImgcropperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CropImg",
			Handler:    _Imgcropper_CropImg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imgcropper.proto",
}
