// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package service

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ImgcroperHTTPServer interface {
	CropImg(context.Context, *CropImgRequest) (*CropImgReply, error)
}

func RegisterImgcroperHTTPServer(s *http.Server, srv ImgcroperHTTPServer) {
	r := s.Route("/")
	r.GET("/getcropimg", _Imgcroper_CropImg0_HTTP_Handler(srv))
}

func _Imgcroper_CropImg0_HTTP_Handler(srv ImgcroperHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CropImgRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.imgcropper.service.Imgcroper/CropImg")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CropImg(ctx, req.(*CropImgRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CropImgReply)
		return ctx.Result(200, reply)
	}
}

type ImgcroperHTTPClient interface {
	CropImg(ctx context.Context, req *CropImgRequest, opts ...http.CallOption) (rsp *CropImgReply, err error)
}

type ImgcroperHTTPClientImpl struct {
	cc *http.Client
}

func NewImgcroperHTTPClient(client *http.Client) ImgcroperHTTPClient {
	return &ImgcroperHTTPClientImpl{client}
}

func (c *ImgcroperHTTPClientImpl) CropImg(ctx context.Context, in *CropImgRequest, opts ...http.CallOption) (*CropImgReply, error) {
	var out CropImgReply
	pattern := "/getcropimg"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.imgcropper.service.Imgcroper/CropImg"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
