// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"newkratos/internal/biz"
	"newkratos/internal/conf"
	"newkratos/internal/data"
	"newkratos/internal/server"
	"newkratos/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	cropImgRepo := data.NewImgCropRepo(dataData, logger)
	cropImgUsecase := biz.NewCropImgUsecase(cropImgRepo, logger)
	imgcroperService := service.NewImgcroperService(cropImgUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, imgcroperService, logger)
	grpcServer := server.NewGRPCServer(confServer, imgcroperService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
